### ISSUE TITLE
Invalid memory access/invokeInt

### ISSUE THREAD

**Issue by tirsod2000** [enigma-dev/lgmplugin#36]
I opened the .gmx on Enigma, I press the "Run" button (After fixing some errors like draw_set_colour being draw_set_color) and this shows up.

Operating System: Windows 8.1
Version: 6.3
Architecture: x86

Java Vendor: Oracle Corporation
Version: 1.8.0_45

Available processors (cores): 4
Free memory (bytes): 212480888
Maximum memory (bytes): 1013645312
Total memory available to JVM (bytes): 259522560

File system root: C:\
Total space (bytes): 500000878592
Free space (bytes): 434361282560
Usable space (bytes): 434361282560

File system root: D:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:

java.lang.Error: Invalid memory access
    at com.sun.jna.Native.invokeInt(Native Method)
    at com.sun.jna.Function.invoke(Function.java:383)
    at com.sun.jna.Function.invoke(Function.java:315)
    at com.sun.jna.Library$Handler.invoke(Library.java:212)
    at com.sun.proxy.$Proxy0.compileEGMf(Unknown Source)
    at org.enigma.EnigmaRunner$CompilerThread.run(EnigmaRunner.java:671)

**Comment by RobertBColton** [comment]
I currently have not been able to reproduce this issue or find a solution at this time. Another Windows XP user has showed up to the IRC channel with the same error message and I was unable to solve it for them after they applied all of the fixes known for common ENIGMA issues.

**Comment by RobertBColton** [comment]
Alright, this issue is getting kind of stale. If you try again and continue to have the same issue, please open a new ticket and I will try to help. For now I am going to close this since a lot has changed since it was last reported and it may not longer be valid.
