### ISSUE TITLE
Prepare gmk to execute in Enigma

### ISSUE THREAD

**Issue by Mikelle02** [enigma-dev/lgmplugin#43]
How can I format a Game Maker file into Enigma to be executed correctly ?  
I tryied many files , even Mode 7 of the Games page of Enigma looks different during the execution in Game Maker and Enigma.

**Comment by RobertBColton** [comment]
Please visit the Wiki page about compatibly differences between ENIGMA and GM.
http://enigma-dev.org/docs/Wiki/GM_Incompatibilities

There are likely to be different ones but ENIGMA settings in some cases allows you to enable additional GM compatibility. If you have a specific compatibility difference please post it on the engine's tracker. This tracker is simply for reporting bugs/errors/exceptions with the LateralGM plugin.
https://github.com/enigma-dev/enigma-dev
