### ISSUE TITLE
Design mode does not work

### ISSUE THREAD

**Issue by MiLattanzio** [enigma-dev/lgmplugin#44]
```
Operating System: Windows 7
Version: 6.1
Architecture: x86

Java Vendor: Oracle Corporation
Version: 1.8.0_73

Available processors (cores): 2
Free memory (bytes): 211780560
Maximum memory (bytes): 1013645312
Total memory available to JVM (bytes): 259522560

File system root: C:\
Total space (bytes): 249892433920
Free space (bytes): 150714298368
Usable space (bytes): 150714298368

File system root: D:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:

java.io.IOException: Unexpected end of file reached at filepos: 0
    at org.lateralgm.file.GmStreamDecoder.read(GmStreamDecoder.java:102)
    at org.lateralgm.file.StreamDecoder.read4(StreamDecoder.java:99)
    at org.enigma.utility.EnigmaBuildReader.readChanges(EnigmaBuildReader.java:44)
    at org.enigma.EnigmaRunner.compile(EnigmaRunner.java:756)
    at org.enigma.EnigmaRunner.actionPerformed(EnigmaRunner.java:786)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    at javax.swing.AbstractButton.doClick(Unknown Source)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by Mikelle02** [comment]
Building for mode (2)
Cleaning up from previous executions
 - Cleared parsed objects
 - Cleared room entries
 - Cleared shared locals list
 - Cleared event info
Loading shared locals from extensions list
Location in memory of structure: 4842e1c0
Copying resources:
Copying sprite names [6]
Copying sound names [0]
Copying background names [0]
Copying path names [0]
Copying script names [4]
Copying shader names [0]
Copying font names [1]
Copying timeline names [0]
Copying object names [2]
Copying room names [2]
Copying constant names [0]
SYNTAX CHECKING AND PRIMARY PARSING:
4 Scripts:
Parsed `scr_player_input': 0 locals, 5 globals
Parsed `scr_savedata': 0 locals, 0 globals
Parsed `scr_save_settings': 0 locals, 0 globals
Parsed `scr_cipher': 0 locals, 0 globals
"Linking" scripts
`Linking' 4 scripts and 0 timelines in 2 passes...
Completing script "Link"
Linking `scr_player_input':
Linking `scr_savedata':
Linking `scr_save_settings':
Linking `scr_cipher':
Done.
Completing timeline "Link"
Done.
2 Objects:
 obj_player: 12 events: 
  Event[0]:   Parsing 1 sub-events:
Check `obj_player::create... Done. Parse... Done.
  Event[3]:   Parsing 1 sub-events:
Check `obj_player::step... Done. Parse... Done.
  Event[7]:   Parsing 1 sub-events:
Check `obj_player::outsideroom... Done. Parse... Done.
 obj_bullet: 12 events: 
  Event[0]:   Parsing 1 sub-events:
Check `obj_bullet::create... Done. Parse... Done.
  Event[7]:   Parsing 1 sub-events:
Check `obj_bullet::outsideroom... Done. Parse... Done.
Creating room creation code scope and parsing
"Linking" scripts into the objects...
"Linking" timelines into the objects...
"Link" complete.
Tabulating maximum argument passes to each script
Finished
Writing executable information and resources.
Writing modes and settings
Writing object switch
Writing resource names and maxima
Writing timeline control information
Linking globals and ambiguous variables
Running Secondary Parse Passes
Add dot accessed local keyboard_wasd
 var 
Add dot accessed local keyboard_arrows
 var 
Add dot accessed local savedata_exists
 var 
Writing events
Writing object data
Writing local accessors
Writing font data
Writing room data
Writing shader data
Running make from `mingw32-make.exe'
Full command line: mingw32-make.exe Game WORKDIR="C:/ProgramData/ENIGMA/" GMODE=Design GRAPHICS=OpenGL1 AUDIO=OpenAL COLLISION=Precise WIDGETS=Win32 NETWORKING=None PLATFORM=Win32 CXXFLAGS="-std=c++11 -I../Additional/i686-w64-mingw32/include" COMPILEPATH="Windows/Windows" EXTENSIONS=" Universal_System/Extensions/DateTime Universal_System/Extensions/Paths Universal_System/Extensions/MotionPlanning Universal_System/Extensions/DataStructures Universal_System/Extensions/Alarms Universal_System/Extensions/BasicGUI Universal_System/Extensions/ParticleSystems Universal_System/Extensions/Timelines" OUTPUTNAME="./ENIGMAsystem/SHELL/design_game.exe" eTCpath=""
mingw32-make.exe -C ENIGMAsystem/SHELL
mingw32-make.exe[1]: Entering directory `C:/Users/Administrator/Desktop/Documenti/Programmazione/Programmi utili/Enigma Portable/ENIGMA/enigma-dev/ENIGMAsystem/SHELL'
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Audio_Systems/OpenAL/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Bridges/Win32-OpenGL1/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Collision_Systems/Precise/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/General/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Platforms/Win32/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/Alarms/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/BasicGUI/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/DataStructures/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/DateTime/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/MotionPlanning/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/Paths/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/Timelines/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Widget_Systems/Win32/
g++ -std=c++11 -I../Additional/i686-w64-mingw32/include -Wall -s -O3 -fno-rtti -fno-exceptions -DPATH_EXT_SET -IPlatforms/Win32/Info -IGraphics_Systems/OpenGL1/Info -IAudio_Systems/OpenAL/Info -ICollision_Systems/Precise/Info -IWidget_Systems/Win32/Info -INetworking_Systems/None/Info -IUniversal_System/Info -I. -IC:/ProgramData/ENIGMA/ -Wall -s -O3 -fno-exceptions  -MMD -MP -c -o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/SHELLmain.o SHELLmain.cpp
mingw32-make.exe[1]: Leaving directory `C:/Users/Administrator/Desktop/Documenti/Programmazione/Programmi utili/Enigma Portable/ENIGMA/enigma-dev/ENIGMAsystem/SHELL'
mingw32-make.exe[1]: Entering directory `C:/Users/Administrator/Desktop/Documenti/Programmazione/Programmi utili/Enigma Portable/ENIGMA/enigma-dev/ENIGMAsystem/SHELL'
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Audio_Systems/OpenAL/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Bridges/Win32-OpenGL1/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Collision_Systems/Precise/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/General/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Platforms/Win32/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/Alarms/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/BasicGUI/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/DataStructures/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/DateTime/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/MotionPlanning/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/Paths/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/Timelines/
mkdir.exe -p C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Widget_Systems/Win32/
echo "// GENERATED RESOURCE FILE FRONTEND" > C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/resources.rc
for res in Preprocessor_Environment_Editable/Resources.rc Widget_Systems/Win32/getstring.rc Widget_Systems/Win32/getlogin.rc Widget_Systems/Win32/showinfo.rc Widget_Systems/Win32/showmessageext.rc; do echo "#include \"$res\"" >> C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/resources.rc; done
windres.exe --codepage=65001 -o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/resources.res -I. -IC:/ProgramData/ENIGMA/ C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/resources.rc -O coff
windres.exe: warning: 24: 1: 1033: duplicate value
windres.exe: warning: 24: 1: 1033: duplicate value
windres.exe: warning: 24: 1: 1033: duplicate value
g++ -L../Additional/i686-w64-mingw32/lib -static-libgcc -static-libstdc++ -o "./ENIGMAsystem/SHELL/design_game.exe" C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/SHELLmain.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/libEGMstd.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Platforms/Win32/WINDOWSjoystick.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Platforms/Win32/WINDOWSmain.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Platforms/Win32/WINDOWSregistry.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Platforms/Win32/WINDOWScallback.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Platforms/Win32/WINDOWSwindow.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Platforms/Win32/WINDOWSfilemanip.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Platforms/Win32/WINDOWSthreads.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Platforms/Win32/WINDOWSsystem.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Platforms/Win32/WINDOWSexternals.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLshader.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLbackground.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLenable.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLscreen.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLtiles.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLstdraw.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLmodel.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLvertex.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLtextures.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLblend.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLTextureStruct.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/OPENGLStd.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLsprite.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLcolors.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLshapes.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLmatrix.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLprofiler.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLd3d.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLprimitives.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/OpenGL1/GLsurface.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/General/GSfont.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/General/GSstdraw.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/General/GSsurface.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/General/GScurves.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/General/GSsprite.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/General/GSmath.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/General/GSbackground.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Graphics_Systems/General/glew.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Audio_Systems/OpenAL/ALsystem.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Audio_Systems/OpenAL/ALadvanced.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Audio_Systems/OpenAL/ALbasic.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Collision_Systems/Precise/PRECimpl.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Collision_Systems/Precise/PRECfuncs.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Collision_Systems/Precise/placeholderlinks.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Widget_Systems/Win32/widgets.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Widget_Systems/Win32/menus.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Widget_Systems/Win32/dialogs.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/CallbackArrays.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/instance_planar.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/object.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/lodepng.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/instance.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/mathnc.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/timelines_object.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/var_array.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/backgroundstruct.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/multifunction_variant.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/highscore_functions.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/loading.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/fontinit.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/rectpack.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/soundinit.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/darray.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/callbacks_events.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/bufferstruct.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/transform_object.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/terminal_io.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/instance_system.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/collisions_object.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/globalupdate.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/move_functions.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/reflexive_types.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/debugscope.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/var4.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/fontstruct.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/fileio.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/planar_object.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/lives.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/shaderstruct.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/dynamic_args.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/spriteinit.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/gif_format.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/estring.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/graphics_object.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/backgroundinit.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/spritestruct.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/ENIGMA_GLOBALS.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/resource_data.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/image_formats.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/zlib.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/roomsystem.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/depth_draw.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/var4_lua.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/DateTime/date_time.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/Paths/path_functions.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/Paths/pathinit.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/Paths/pathstruct.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/MotionPlanning/mp_movement.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/MotionPlanning/motion_planning.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/MotionPlanning/motion_planning_struct.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/DataStructures/data_structures.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/Alarms/alarmcode.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/BasicGUI/buttons.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/BasicGUI/windows.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/BasicGUI/skins.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/BasicGUI/toggles.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/BasicGUI/sliders.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/BasicGUI/styles.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/BasicGUI/labels.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/BasicGUI/groups.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_effects.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_particle_emitter.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_particle_attractor.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_actions.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_particle_changer.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_particle_updatedraw.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_particle_deflector.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_particle_destroyer.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_particle_particles_apiimpl.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_particle_sprites.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_particle_type.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_particle_system_apiimpl.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_particle_depths.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_particle_system_manager.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/ParticleSystems/PS_particle_system.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Universal_System/Extensions/Timelines/timelines.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/Bridges/Win32-OpenGL1/graphics_bridge.o C:/ProgramData/ENIGMA/.eobjs/Windows/Windows/Design/resources.res -lffi -lcomdlg32 -lgdi32 -lwinmm -lwininet -lopengl32 -lglu32 -lALURE32-static -lOpenAL32 -lvorbisfile -lvorbis -logg -lFLAC -lsndfile -lmodplug -lmpg123 -lole32 -lwinmm -lcomctl32 -luuid -lole32 -lz
ndows/Windows/Design/resources.res -lffi -lcomdlg32 -lgdi32 -lwinmm -lwininet -lopengl32 -lglu32 -lALURE32-static -lOpenAL32 -lvorbisfile -lvorbis -logg -lFLAC -lsndfile -lmodplug -lmpg123 -lole32 -lwinmm -lcomctl32 -luuid -lole32 -lz
ndows/Windows/Design/resources.res -lffi -lcomdlg32 -lgdi32 -lwinmm -lwininet -lopengl32 -lglu32 -lALURE32-static -lOpenAL32 -lvorbisfile -lvorbis -logg -lFLAC -lsndfile -lmodplug -lmpg123 -lole32 -lwinmm -lcomctl32 -luuid -lole32 -lz
c:/users/administrator/desktop/documenti/programmazione/programmi utili/enigma portable/enigma/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.8.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot open output file ./ENIGMAsystem/SHELL/design_game.exe: No such file or directory
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[1]: *** [compile_game] Error 1
mingw32-make.exe[1]: Leaving directory `C:/Users/Administrator/Desktop/Documenti/Programmazione/Programmi utili/Enigma Portable/ENIGMA/enigma-dev/ENIGMAsystem/SHELL'
mingw32-make.exe: *** [Game] Error 2
c:/users/administrator/desktop/documenti/programmazione/programmi utili/enigma portable/enigma/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.8.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot open output file ./ENIGMAsystem/SHELL/design_game.exe: No such file or directory
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[1]: *** [compile_game] Error 1
mingw32-make.exe[1]: Leaving directory `C:/Users/Administrator/Desktop/Documenti/Programmazione/Programmi utili/Enigma Portable/ENIGMA/enigma-dev/ENIGMAsystem/SHELL'
mingw32-make.exe: *** [Game] Error 2
c:/users/administrator/desktop/documenti/programmazione/programmi utili/enigma portable/enigma/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.8.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot open output file ./ENIGMAsystem/SHELL/design_game.exe: No such file or directory
collect2.exe: error: ld returned 1 exit status
mingw32-make.exe[1]: *** [compile_game] Error 1
mingw32-make.exe[1]: Leaving directory `C:/Users/Administrator/Desktop/Documenti/Programmazione/Programmi utili/Enigma Portable/ENIGMA/enigma-dev/ENIGMAsystem/SHELL'
mingw32-make.exe: *** [Game] Error 2

**Comment by RobertBColton** [comment]
ENIGMA currently does not support spaces in its installation path. Please move it to C:/Users/MyUserName/Desktop/ENIGMA or to C:/ENIGMA or any other path that does not contain spaces. If this does not work please let us know.

**Comment by RobertBColton** [comment]
What seems odd is that OUTPUTNAME="./ENIGMAsystem/SHELL/design_game.exe" where in my build it is OUTPUTNAME="C:/Users/Owner/AppData/Local/Temp/egm916633198709335388.exe"

Did you specifically tell it to compile the game in that folder using the compile button instead of run?

**Comment by RobertBColton** [comment]
Could you please upload and share the game that causes this to fail? Also please share the exact steps you follow from opening ENIGMA to compiling the game.

**Comment by RobertBColton** [comment]
These issues occur when running in Design mode. It currently does not work and has not worked since ENIGMA r4 but will be implemented again at a future point in time. For now stick to run/debug/compile.
