### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Eanmos** [enigma-dev/lgmplugin#45]
Operating System: Windows XP
Version: 5.1
Architecture: x86

Java Vendor: Oracle Corporation
Version: 1.8.0_91

Available processors (cores): 1
Free memory (bytes): 225305168
Maximum memory (bytes): 1013645312
Total memory available to JVM (bytes): 259522560

File system root: A:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: C:\
Total space (bytes): 78954426368
Free space (bytes): 15406936064
Usable space (bytes): 15406936064

File system root: D:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

File system root: E:\
Total space (bytes): 78192640
Free space (bytes): 0
Usable space (bytes): 0

File system root: F:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:

java.lang.Error: Invalid memory access
	at com.sun.jna.Native.invokePointer(Native Method)
	at com.sun.jna.Function.invokePointer(Function.java:470)
	at com.sun.jna.Function.invokeString(Function.java:651)
	at com.sun.jna.Function.invoke(Function.java:395)
	at com.sun.jna.Function.invoke(Function.java:315)
	at com.sun.jna.Library$Handler.invoke(Library.java:212)
	at com.sun.proxy.$Proxy0.libInit(Unknown Source)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:191)

**Comment by RobertBColton** [comment]
Hi! Please create the folder C:/ProgramData or point enigma-dev/settings.ey on the line https://github.com/enigma-dev/enigma-dev/blob/208ddf8dfbff3c9fc4f050c87bd605ee04bc5452/settings.ey#L49 to an alternative location that does exist for ENIGMA to compile your game to. The issue is caused by Windows XP not supporting the ProgramData folder.
