### ISSUE TITLE
Feature: asset_get_index();

### ISSUE THREAD

**Issue by Kayomn** [enigma-dev/lgmplugin#46]
I'm not sure about anyone else, but I find this function to be a very handy feature. It's pretty simple, it just takes the string input and converts it into the name of resource, allowing you to do for example:

`var shirtSprite;`
`shirtSprite = asset_get_type("spr_"+playerShirt);`

`draw_sprite(shirtSprite,0,x,y);`

It's a very simple function that allows for a world off difference as far as making items easier to assign to the the character, by not making you use more convoluded ways of assigning things like assets to an object.

In Game Maker the command works with all resources as far as I can tell (backgrounds, objects, sprites, etc.). I'm hoping this gets implemented in the future as it's a really handy feature of Game Maker.

**Comment by faissaloo** [comment]
You've posted this in the wrong place, since this concerns ENIGMA itself it should go here: https://github.com/enigma-dev/enigma-dev

**Comment by Kayomn** [comment]
Apologies, gonna close this then.
