### ISSUE TITLE
Unknown Problem...When I updated to v1.8.7.11

### ISSUE THREAD

**Issue by Armcoon** [enigma-dev/lgmplugin#47]
Operating System: Windows 7
Version: 6.1
Architecture: x86

Java Name: Java HotSpot(TM) Client VM
Java Vendor: Oracle Corporation
Version: 1.7.0_25

Available processors (cores): 4
Free memory (bytes): 194885872
Maximum memory (bytes): 1013645312
Total memory available to JVM (bytes): 259522560

File system root: C:\
Total space (bytes): 320070479872
Free space (bytes): 37206200320
Usable space (bytes): 37206200320

File system root: Q:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:

java.lang.NoSuchFieldError: gameSettings
	at org.enigma.EnigmaWriter.populateSettings(EnigmaWriter.java:225)
	at org.enigma.EnigmaWriter.populateStruct(EnigmaWriter.java:155)
	at org.enigma.EnigmaWriter.prepareStruct(EnigmaWriter.java:133)
	at org.enigma.EnigmaRunner$CompilerThread.run(EnigmaRunner.java:668)

**Comment by RobertBColton** [comment]
Hi, did you also download the new plugin at the same time? It is required for the new LGM.

http://enigma-dev.org/docs/Wiki/Install:Extra_Packages

**Comment by Armcoon** [comment]
Thanks you report, ENGIMA developer. 😄

**Comment by RobertBColton** [comment]
No problem, glad that resolved the issue!
