### ISSUE TITLE
EGM Issue

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/lgmplugin#50]
This was brought up in https://github.com/IsmAvatar/LateralGM/issues/246 by @Woffelson

Well, I couldn't reproduce the bug identically since the saved project didn't corrupt this time. However, when I saved the project earlier in EGM-format, it gave this following error. The file is [here](http://files.1337upload.net/plattis-77140f.zip).

```
Operating System: Linux
Version: 3.13.0-74-generic
Architecture: amd64

Java Vendor: Oracle Corporation
Version: 1.7.0_91

Available processors (cores): 2
Free memory (bytes): 121153056
Maximum memory (bytes): 1392508928
Total memory available to JVM (bytes): 171442176

File system root: /
Total space (bytes): 236154146816
Free space (bytes): 39917527040
Usable space (bytes): 27897962496

Stack trace:
java.lang.NullPointerException
    at org.enigma.file.EFileReader.readResource(EFileReader.java:666)
    at org.enigma.file.EFileReader.processEntries(EFileReader.java:644)
    at org.enigma.file.EFileReader.readNodeChildren(EFileReader.java:622)
    at org.enigma.file.EFileReader.readEgmFile(EFileReader.java:560)
    at org.enigma.file.EFileReader.readEgmFile(EFileReader.java:538)
    at org.enigma.file.EgmIO.read(EgmIO.java:56)
    at org.lateralgm.main.FileChooser$1.run(FileChooser.java:564)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by SuperRiderTH** [comment]
Any EGM I try to open gives me this error. I created an EGM with a new object, saved it, opened it, got the error. The object does load though. 
![screenshot from 2017-05-17 17-08-17](https://cloud.githubusercontent.com/assets/5368844/26176415/11d4c098-3b24-11e7-974e-0d850140501e.png)


However, I have some EGMs from a while back that do not open properly.

![screenshot from 2017-05-17 17-14-03](https://cloud.githubusercontent.com/assets/5368844/26176467/3fa0e812-3b24-11e7-9272-896e7c8e29fe.png)

**Comment by RobertBColton** [comment]
Closing as #82 covers the EGM format being disabled now due to issues like this.
