### ISSUE TITLE
Unable to load library 'compileEGMf': Native library (darwin/libcompileEGMf.dylib) not found in resource path

### ISSUE THREAD

**Issue by ArthoPacini** [enigma-dev/lgmplugin#51]
The compile/debug and create application buttons stays grey

my Java version is the Java 8 update 101

i execute 

> java -jar lateralgm.jar

and that's it

```

Operating System: Mac OS X
Version: 10.11.6
Architecture: x86_64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_101

Available processors (cores): 2
Free memory (bytes): 40827800
Maximum memory (bytes): 716177408
Total memory available to JVM (bytes): 64487424

File system root: /
Total space (bytes): 79166603264
Free space (bytes): 28056158208
Usable space (bytes): 27794014208

Stack trace:

java.lang.UnsatisfiedLinkError: Unable to load library 'compileEGMf': Native library (darwin/libcompileEGMf.dylib) not found in resource path ([file:/Users/arthopacini/Desktop/enigmadev/LateralGM-master/plugins/enigma.jar])
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
    at com.sun.jna.Library$Handler.<init>(Library.java:147)
    at com.sun.jna.Native.loadLibrary(Native.java:412)
    at com.sun.jna.Native.loadLibrary(Native.java:391)
    at org.enigma.EnigmaRunner.attemptLib(EnigmaRunner.java:248)
    at org.enigma.EnigmaRunner.access$1(EnigmaRunner.java:241)
    at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:179)

```

**Comment by RobertBColton** [comment]
Try the following:
```
cd enigma-dev/CompilerSource
make
cd ..
java -jar lateralgm.jar
```

**Comment by ArthoPacini** [comment]
got the same `Unable to load library 'compileEGMf': Native library (darwin/libcompileEGMf.dylib) not found in resource path ([file:/Users/arthopacini/Desktop/enigma/plugins/enigma.jar])`

**Comment by RobertBColton** [comment]
@RodrigoCard do you think you could offer him some help here please? I don't have a Mac and I don't have much experience setting it up.

**Comment by RodrigoCard** [comment]
@RobertBColton Of course :)

@ArthoPacini You get this error because the Library was not built, it is not a problem with the plugin.

Please follow this pull request, I need to make a few changes before it can be accepted, but you can try yourself if you want https://github.com/enigma-dev/enigma-dev/pull/1011

You can also download this pre-built library I made, and put the in same folder of lateralgm Jar file:
https://dl.dropboxusercontent.com/u/14890209/dev/libcompileEGMf.dylib.zip

**Comment by ArthoPacini** [comment]
Funcionou! Eu consegui abrir o lateralgm e o plugin abriu normalmente sem nenhum erro, porém quando eu compilo, ele dá Compile failed at C++ level.

eu entrei em todas as pastas que tinha makefile e fiz o make, o erro só se prolongou durante a compilaçao.

![image](https://cloud.githubusercontent.com/assets/22568556/22616373/f2fafd22-ea92-11e6-86a8-57c52749bb95.png)

**Comment by RobertBColton** [comment]
Closing as stsale now all development has moved to RGM
