### ISSUE TITLE
Unable to load library 'compileEGMf' on windows 7/ 10

### ISSUE THREAD

**Issue by blastnote** [enigma-dev/lgmplugin#55]
`Operating System: Windows 7
Version: 6.1
Architecture: amd64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 1.8.0_144

Available processors (cores): 4
Free memory (bytes): 197617704
Maximum memory (bytes): 932184064
Total memory available to JVM (bytes): 257425408

File system root: C:\
Total space (bytes): 487467274240
Free space (bytes): 143591239680
Usable space (bytes): 143591239680

File system root: E:\
Total space (bytes): 31917604864
Free space (bytes): 31182831616
Usable space (bytes): 31182831616

File system root: I:\
Total space (bytes): 0
Free space (bytes): 0
Usable space (bytes): 0

Stack trace:

java.lang.UnsatisfiedLinkError: Unable to load library 'compileEGMf': Native library (win32-x86-64/compileEGMf.dll) not found in resource path ([file:/C:/Users/nichbrin2/Desktop/enigma/ENIGMA/enigma-dev/plugins/enigma.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:412)
	at com.sun.jna.Native.loadLibrary(Native.java:391)
	at org.enigma.EnigmaRunner.attemptLib(EnigmaRunner.java:248)
	at org.enigma.EnigmaRunner.access$1(EnigmaRunner.java:241)
	at org.enigma.EnigmaRunner$3.run(EnigmaRunner.java:179)
`

This is the case across multiple devices on both Virtual machines and actual operating systems
#49

**Comment by PrOF-kk** [comment]
Can confirm on Winndows 10
Any known workarounds?

**Comment by JoshDreamland** [comment]
Make sure that the architecture of your Java release matches the architecture you built ENIGMA for. If you used a 32-bit GCC to build ENIGMA (or you are using Robert's pre-packaged ENIGMA zip), run LGM with a 32-bit Java. If you downloaded MSys yourself, it's probably 64-bit, so make sure you're running with a 64-bit Java.

**Comment by RobertBColton** [comment]
Exactly what Josh said. You can install a 32 bit Java without uninstalling the 64 bit one, just change the setting for ENIGMA to launch through the 32 bit Java:
https://enigma-dev.org/docs/Wiki/Install:Parallel_Java

**Comment by RobertBColton** [comment]
Closing the issue as stale, confirmed as incompatible Java and workaround was given.
