### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Domosed-gamin** [enigma-dev/lgmplugin#69]
```
`g++ -fPIC -std=c++11 -Wall -O3 -g -I./JDI/src -I../shared -I../shared/libpng-util -I../shared/protos/codegen  -I. -MMD -MP -c -o .eobjs/./compiler/compile.o compiler/compile.cpp
compiler/compile.cpp: In member function ‘virtual int lang_CPP::compile(const GameData&, const char*, int)’:
compiler/compile.cpp:430:57: error: no match for ‘operator[]’ (operand types are ‘const google::protobuf::RepeatedPtrField<buffers::resources::Timeline_Moment>’ and ‘int’)
         wto << "  curr[" << game.timelines[i]->moments()[j].step()
`
```

**Comment by Domosed-gamin** [comment]
Please help me to fix this error, guys.

**Comment by RobertBColton** [comment]
First, the protobuf you used is too old, the `[]` operator was added about 2 years ago. You need to either build protobuf yourself, upgrade your operating system, or install protobuf from a ppa.

The compileEGMf error is actually directly the fault of the first error. The compileEGMf library is used by this plugin, which loads it with JNA, to communicate resources to ENIGMA's compiler such as objects, roms, and code. You got the first error while building compileEGMf, hence it doesn't exist.

**Comment by Domosed-gamin** [comment]
@RobertBColton Ok. I built protobuf. I have new problem. When I compile every game, I have error.

`n file included from /usr/include/glm/detail/type_int.hpp:6:0,
                 from /usr/include/glm/fwd.hpp:6,
                 from /usr/include/glm/glm.hpp:61,
                 from Graphics_Systems/General/GSmatrix_impl.h:36,
                 from Graphics_Systems/General/GSmodel.cpp:28:
/usr/include/glm/detail/setup.hpp:654:3: error: #error Define GLM_FORCE_LEFT_HANDED instead of GLM_LEFT_HANDED left handed coordinate system by default.
 # error Define GLM_FORCE_LEFT_HANDED instead of GLM_LEFT_HANDED left handed coordinate system by default.
   ^~~~~
g++ -std=c++11 -Wall -s -O3 -fno-rtti -fno-exceptions -IBridges/OpenGL -DPATH_EXT_SET -I../../shared/libpng-util -IPlatforms/xlib/Info -IGraphics_Systems/OpenGL1/Info -IAudio_Systems/OpenAL/Info -ICollision_Systems/Precise/Info -IWidget_Systems/None/Info -INetworking_Systems/None/Info -IUniversal_System/Info -I. -I/home/ringo/.enigma/ -I../../shared  -MMD -MP -c -o /home/ringo/.enigma/.eobjs/Linux/Linux/GNU_GCC_G++/Run/Graphics_Systems/OpenGL1/GLd3d.o Graphics_Systems/OpenGL1/GLd3d.cpp
In file included from /usr/include/glm/detail/type_int.hpp:6:0,
                 from /usr/include/glm/fwd.hpp:6,
                 from /usr/include/glm/glm.hpp:61,
                 from ./Graphics_Systems/General/GSmatrix_impl.h:36,
                 from Graphics_Systems/OpenGL1/GLd3d.cpp:29:
/usr/include/glm/detail/setup.hpp:654:3: error: #error Define GLM_FORCE_LEFT_HANDED instead of GLM_LEFT_HANDED left handed coordinate system by default.
 # error Define GLM_FORCE_LEFT_HANDED instead of GLM_LEFT_HANDED left handed coordinate system by default.
   ^~~~~
rm -f /home/ringo/.enigma/.eobjs/Linux/Linux/GNU_GCC_G++/Run/Universal_System/loading.o /home/ringo/.enigma/.eobjs/Linux/Linux/GNU_GCC_G++/Run/Universal_System/Extensions/MotionPlanning/motion_planning.o`

**Comment by RobertBColton** [comment]
Now your GLM is outdated, another user has this issue and I frequently have to help them with it.
https://github.com/enigma-dev/enigma-dev/issues/1457

For now, just go to the following file and comment out `GLM_LEFT_HANDED` but leave `GLM_FORCE_LEFT_HANDED` alone.
https://github.com/enigma-dev/enigma-dev/blob/fefa7f5e37bd8c22ef8d5c0a9d8bd922919e6118/ENIGMAsystem/SHELL/Graphics_Systems/General/GSmatrix_impl.h#L33

**Comment by RobertBColton** [comment]
Please let me know or close the issue if that resolves it (which it should).

**Comment by Domosed-gamin** [comment]
@ @RobertBColton Sorry. It's work fine now. Thank you! Install enigma is almost impossible puzzle. Really hard for non-programmer. Please make easier.

**Comment by RobertBColton** [comment]
You are very welcome, and I'm glad you did get it working! I am aware of the technicalities yes, and we'd like to do something to fix it. I've been considering an automated installer generator to make things easier.  But we'll have to see. For now though, we are totally fine with third parties creating installers and or Debian/Arch packages.
